# Manifest file for Eureka Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: eureka-dev
  template:
    metadata:
      labels:
        name: eureka-dev
    spec:
      containers:
        - image: dit
          name: eureka-dev
          
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-dev-svc
spec:
  selector:
    name: eureka-dev
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8761